server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**,/db_order/**
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**,/db_delivery/**
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**,/db_payment/**
        - id: orderpage
          uri: http://localhost:8084
          predicates:
            - Path=/orderPages/**,/db_orderpage/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**,/db_order/**
        - id: delivery
          uri: http://cafe:8080
          predicates:
            - Path=/deliveries/**,/db_delivery/**
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**,/db_payment/**
        - id: orderpage
          uri: http://orderpage:8080
          predicates:
            - Path=/orderPages/**,/db_orderpage/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
